<img src="Images/PU.png" width="100%">

## Course Name : Python for Data Analysis 
#### Notebook compiled by : Rajiv Kale, Consultant at Learning and Development  
** Important ! ** For internal circulation only

# Assignment on Numpy

**1. Write a NumPy program to convert a Python list of numeric value into a one-dimensional NumPy array and print both.**

In [1]:
import numpy as np
l = [12.23, 13.32, 100, 36.32]
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array:  [ 12.23  13.32 100.    36.32]


**2. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.**

Expected Output:
    
[[ 2 3 4]
 
[ 5 6 7]

 [ 8 9 10]]

In [13]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


**3. Write a NumPy program to compute the multiplication of two given matrixes.**

In [15]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.dot(p, q)
print("Result of the said matrix multiplication:")
print(result1)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Result of the said matrix multiplication:
[[1 2]
 [3 4]]


**4. Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis.**

**Hint:** Use np.ptp() function. Look at the documentation.
    
numpy.ptp()functions use to plays an important role in statistics by finding out Range of given numbers. Range = max value – min value.
    
axis :axis along which we want the range value. Otherwise, it will consider arr to be flattened(works on all the axis). axis = 0 means along the column and axis = 1 means working along the row.

Original array:
    
[[ 0 1 2 3 4 5]

 [ 6 7 8 9 10 11]]

Expected Output:
    
Difference between the maximum and the minimum values of the said array:

[5 5]

In [19]:
import numpy as np
x = np.arange(12).reshape((2, 6))
print("\nOriginal array:")
print(x)
r1 = np.ptp(x, 1)
print(r1)


Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[5 5]


In [18]:
r2 = np.amax(x, 1) - np.amin(x, 1)
assert np.allclose(r1, r2)
print(r1)

[5 5]


**5. Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis.**

**Hint:** Use np.percentile function. Look at the documentation.    

In [24]:
import numpy as np
x = np.arange(12).reshape((2, 6))
print("\nOriginal array:")
print(x)
r1 = np.percentile(x, 80, 1)
print("\n80th percentile for all elements of the said array along the second axis:")
print(r1)


Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

80th percentile for all elements of the said array along the second axis:
[ 4. 10.]
